services:
  oracle-db:
    image: gvenzl/oracle-xe
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
      - ORACLE_DATABASE=XEPDB1
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./src/main/resources/db/init.sql:/container-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//oracle-db:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=oracle
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=${JAVA_TOOL_OPTIONS}
    depends_on:
      oracle-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 5

volumes:
  oracle-data: